data:
  feature_extraction:
    max_df: 0.95
    max_features: 10000
    min_df: 2
    ngram_range:
    - 1
    - 3
  processed_data_path: data/processed/
  raw_data_path: data/raw/
  raw_data_urls:
    test: https://raw.githubusercontent.com/thiagorainmaker77/liar_dataset/master/test.tsv
    train: https://raw.githubusercontent.com/thiagorainmaker77/liar_dataset/master/train.tsv
    valid: https://raw.githubusercontent.com/thiagorainmaker77/liar_dataset/master/valid.tsv
  text_cleaning:
    convert_lowercase: true
    min_word_length: 2
    remove_hashtags: false
    remove_mentions: true
    remove_punctuation: true
    remove_stopwords: true
    remove_urls: true
evaluation:
  metrics:
  - accuracy
  - precision
  - recall
  - f1
  - roc_auc
  - confusion_matrix
  plot_settings:
    dpi: 300
    figure_size:
    - 12
    - 8
    plot_format: png
    save_plots: true
models:
  algorithms:
  - RandomForest
  - XGBoost
  - LightGBM
  - LogisticRegression
  - SVM
  best_model_name: best_fake_news_detector
  cross_validation:
    n_folds: 10
    random_state: 42
    shuffle: true
    stratify: true
  hyperparameter_tuning:
    method: grid_search
    n_trials: 10
    timeout: 3600
  model_save_path: models/trained_models/
output:
  figures_path: results/figures/
  log_file: fake_news_detection.log
  log_level: INFO
  metrics_path: results/metrics/
  reports_path: results/reports/
  results_path: results/
reproducibility:
  ensure_reproducibility: true
  random_seed: 42
training:
  early_stopping:
    enabled: true
    min_delta: 0.001
    patience: 10
  random_state: 42
  test_size: 0.2
  validation_size: 0.1
